server:
 port: 8300
spring:
 cloud:
  gateway:
   routes:
    -id: account
     uri: "lb://ACCOUNT"
     pradicate:
      -path:"/account/**"
    -id: cards
     uri: "lb://CARDS"
     pradicate:
      -path:"/cards/**"
    -id: loans
     uri: "lb://LOANS"
     pradicate:
      -path:"/loans/**"
    
