server:
  port: 8500

spring:
  application:
    name: "eurekaserver"
  config:
    import: "configserver:http://localhost:8000/"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: "http://localhost:${server.port}/eureka/"
info:
  app:
    name: eureka-server
    description: handle all microservice application
    version: 1.0.0